version: '2'

services:
  kong:
    image: kong:1.1.2-alpine
    restart: always
    depends_on:
      - db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: db
      KONG_PG_PORT: 5432
      KONG_PG_USER: kong
      KONG_PG_DATABASE: kong
      KONG_PG_PASSWORD: password
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG:  /dev/stderr
      KONG_ADMIN_ERROR_LOG:  /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    command: sh -c "kong migrations bootstrap && /docker-entrypoint.sh kong docker-start"
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kong
    volumes:
      - ./db:/var/lib/postgres/data
